// One-shot helper: generate a restaurant ambience clip via ElevenLabs Sound
// Generation and attach it to a Conversational AI agent as background audio.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.95.0";
import { encodeBase64 as b64encode } from "https://deno.land/std@0.224.0/encoding/base64.ts";

const ELEVENLABS_API_KEY = Deno.env.get("ELEVENLABS_API_KEY")!;
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

async function generateAmbience(prompt: string, duration: number): Promise<Uint8Array> {
  const res = await fetch("https://api.elevenlabs.io/v1/sound-generation", {
    method: "POST",
    headers: { "xi-api-key": ELEVENLABS_API_KEY, "Content-Type": "application/json" },
    body: JSON.stringify({ text: prompt, duration_seconds: duration, prompt_influence: 0.4, loop: true }),
  });
  if (!res.ok) throw new Error(`sound-generation ${res.status}: ${await res.text()}`);
  return new Uint8Array(await res.arrayBuffer());
}

async function attachBackground(agentId: string, mp3: Uint8Array, volume: number) {
  const dataUri = `data:audio/mpeg;base64,${b64encode(mp3)}`;
  const body = {
    conversation_config: {
      agent: {
        background_audio: { enabled: true, volume, source: dataUri },
      },
    },
  };
  const res = await fetch(`https://api.elevenlabs.io/v1/convai/agents/${agentId}`, {
    method: "PATCH",
    headers: { "xi-api-key": ELEVENLABS_API_KEY, "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`agent patch ${res.status}: ${text}`);
  return text;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
  try {
    const { agent_id, prompt, duration_seconds, volume } = await req.json().catch(() => ({}));
    const promptText = prompt || "Busy upscale restaurant ambience: distant murmur of conversations, soft cutlery clinks, gentle background music, warm room tone. No distinct voices, no sudden noises, smooth and loopable.";
    const duration = Math.min(Math.max(Number(duration_seconds) || 22, 5), 22);
    const vol = typeof volume === "number" ? Math.max(0, Math.min(1, volume)) : 0.15;

    const mp3 = await generateAmbience(promptText, duration);
    console.log("[agent-set-background-audio] generated bytes", mp3.byteLength);

    const sb = createClient(SUPABASE_URL, SERVICE_KEY);
    let agentIds: string[] = [];
    if (agent_id) {
      agentIds = [agent_id];
    } else {
      const { data } = await sb.from("agents").select("elevenlabs_agent_id").not("elevenlabs_agent_id", "is", null);
      agentIds = (data || []).map((a: any) => a.elevenlabs_agent_id);
    }
    if (!agentIds.length) {
      return new Response(JSON.stringify({ error: "no agents to update" }), { status: 400, headers: { ...cors, "Content-Type": "application/json" } });
    }

    const results: any[] = [];
    for (const id of agentIds) {
      try {
        await attachBackground(id, mp3, vol);
        results.push({ agent_id: id, ok: true });
      } catch (e) {
        results.push({ agent_id: id, ok: false, error: String(e) });
      }
    }
    return new Response(JSON.stringify({ ok: true, volume: vol, duration, mp3Bytes: mp3.byteLength, results }), {
      headers: { ...cors, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("[agent-set-background-audio] failed", e);
    return new Response(JSON.stringify({ error: String(e) }), { status: 500, headers: { ...cors, "Content-Type": "application/json" } });
  }
});
